[package]
name = "rootcause"
version = "0.8.1"
edition = "2024"
license = "MIT/Apache-2.0"
description = "A flexible, ergonomic, and inspectable error reporting library for Rust"
repository = "https://github.com/rootcause-rs/rootcause"

[workspace]
members = ["rootcause-internals"]

[features]
default = []
std = ["indexmap/std", "triomphe/std", "anyhow?/std"]
backtrace = ["dep:backtrace", "dep:regex", "std"]
anyhow = ["dep:anyhow"]

[dependencies]
hashbrown = { version = "0.16.0", default-features = false }
indexmap = { version = "2.12.0", default-features = false }
rustc-hash = { version = "2.1.1", default-features = false }
spin = { version = "0.10.0", default-features = false, features = ["rwlock"] }
triomphe = { version = "0.1.15", default-features = false, features = [
  "unsize",
] }
unsize = "1.1.0"

# Optional dependencies
anyhow = { version = "1.0.100", optional = true, default-features = false }
backtrace = { version = "0.3.76", optional = true, features = ["cpp_demangle"] }
regex = { version = "1.12.2", optional = true }

# Internal dependencies
rootcause-internals = { path = "rootcause-internals", version = "=0.8.1" }

[dev-dependencies]
indexmap = "2.12.0"
serde_json = "1.0.145"
static_assertions = "1.1.0"
thiserror = "2.0.17"

derive_more = { version = "2.0", default-features = false, features = [
  "error",
  "from",
  "display",
] }

[[example]]
name = "anyhow_interop"
required-features = ["anyhow"]

[[example]]
name = "anyhow_migration"
required-features = ["anyhow"]

[package.metadata.docs.rs]
all-features = true

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(nightly_extra_checks)'] }
