name: Tests

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches: ["main"]
  merge_group:
  pull_request:
  schedule:
    - cron: "32 4 * * 5"
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: ["1.89", stable, beta]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2

      - name: Run fmt
        run: cargo fmt --check

      - name: Run clippy
        run:
          cargo clippy -p rootcause -p rootcause-backtrace --all-targets -- -D warnings
          cargo clippy -p rootcause -p rootcause-backtrace --all-targets --all-features -- -D warnings
          cargo clippy -p rootcause-internals -- -D warnings

      - name: Run tests
        run: cargo test --workspace --all-targets && cargo test --workspace --all-targets --all-features

      - name: Run doctests
        run: cargo test --workspace --doc && cargo test --workspace --doc --all-features

      - name: Run docs
        run: cargo doc --no-deps -p rootcause -p rootcause-internals -p rootcause-backtrace --all-features

      - name: Run cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          rust-version: ${{ matrix.rust }}

  miri:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: miri rust-src
      - uses: Swatinem/rust-cache@v2

      - name: Run tests with miri
        run: |
          export MIRIFLAGS="-Zmiri-strict-provenance -Zmiri-isolation-error=warn"

          cargo miri test --workspace --all-targets
          cargo miri test --workspace --all-features --all-targets

          cargo miri test --workspace --doc
          cargo miri test --workspace --doc --all-features
